### PR TITLE
chore: training cards for FAB

### PR DESCRIPTION
**Pull request by latin-panda**
Training cards for [FAB](https://github.com/medic/cht-core/issues/7998)

### CODE REVIEW

**Comment by latin-panda** [comment]
@michaelkohn please review, this is based on Nicole's design for PIH training cards

Screenshot 2023-04-27 at 12 52 36 pm

**Comment by michaelkohn** [comment]
@n-orlowski is making some tweaks to the content. We can merge this once those are done.

**Comment by latin-panda** [comment]
Hi @michaelkohn @n-orlowski, is the content ready?

**Comment by n-orlowski** [comment]
@latin-panda not yet, I misunderstood as we made the changes directly in Chichewa but I'll have this ready by EOD :)

**Comment by n-orlowski** [comment]
There have been some important changes to your app. 

Tap **next** to see what your app used to look like, and what it looks like now.

------

The action bar at the bottom has changed. It used to look like this. 

Screen Shot 2023-05-10 at 11 48 16 AM

------

In your new app, the action bar is now a button that looks like this.

[same image]

------

Tap on this button to view to add people and access your forms.

[same image]

------

If you understand these changes and are ready to start using your app, tap on **Submit**.

If you have any questions or need further instructions, please contact your supervisor.

**Comment by latin-panda** [comment]
@n-orlowski and @michaelkohn please review

**Review by michaelkohn — APPROVED** [review]
LGTM!

**Pull request merged**
