### PR TITLE
Adding dark-mode favicon capability and images

### LINKED ISSUE #924: Set up light and dark favicons
Currently we just have one option, which is good on light/regular windows, but not so good on "dark" themes:
image

The following format seems to be the recommended approach for letter the browser show the desired image for the current UI theme:

```
<link rel="icon" media="(prefers-color-scheme: dark)"  href="/icons/favicon-dark.png">
<link rel="icon" media="(prefers-color-scheme: light)"  href="/icons/favicon-light.png">
```

### PR DESCRIPTION
**Pull request by craig-landry**
Resolves #924

Our current theme inherits from docsy and the favicons are generates from the following template: https://github.com/google/docsy/blob/1d126ab1bbf186fa0ea52a6d6a3f58229b2b7942/layouts/partials/favicons.html

This changes adds a new favicon layout to override the base. The new layout is the same as the base, but adds the media attribute to supply browsers with light/dark options should they choose to respect it.

White color images are included for all sizes for the dark option.

Here's how this looks on Firefox 180 on Ubuntu Linux with the dark themed UI in Gnome:
image

### CODE REVIEW

**Review by abbyad — CHANGES_REQUESTED** [review]
I had a feeling dark mode was going to elicit follow-up 😁

As mentioned in https://github.com/medic/cht-docs/issues/900#issuecomment-1363401069 I think we should have a single favicon that better well with a variety of tab colors.

**Comment by craig-landry** [comment]
@abbyad From our video conversation about this, did you end up finding a single icon that works for dark/light? I'd like to close this if we don't intend on using it.

**Comment by abbyad** [comment]
I have a better one but haven't committed it yet. Do you want that new icon as part of this PR, or a wholly new one? Either way it still relates to https://github.com/medic/cht-docs/issues/924.

**Comment by craig-landry** [comment]
Let's just do it as a separate PR. I'm going to close this one and will take a look at your new one when you open it.

**Pull request closed without merging**
