### PR TITLE
fail on bad builds in CI earlier

### PR DESCRIPTION
**Pull request by mrjones-plip**
This build adds a call to `hugo build` that exposes bad builds earlier on in the CI process.  We had [an issue where](https://github.com/medic/cht-docs/pull/298#issuecomment-685180595) a broken build was pushed and CI broke at the `All Branches - Run Muffet link checker` stop in a very non obvious way with:

```
dial tcp4 127.0.0.1:1313: connect: connection r#299 ed
##[error]Process completed with exit code 1.
```

This PR fixes that by explicitly running `hugo` early the CI process and it's called "All Branches - Test For Broken Builds in Hugo" so editors will know why their branch isn't passing CI when it breaks.

see #299

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@nomulex  - Ready for review!

**Comment by mrjones-plip** [comment]
FYI @abbyad

**Comment by mrjones-plip** [comment]
oh @alixemden  - let me know if you can't override @MaxDiz being a reviewer, given he's out on paternal leave.

**Comment by abbyad** [comment]
I just removed @MaxDiz as reviewer.

**Comment by nomulex** [comment]
LGTM.  I am felling like prophet this morning. I remember mentioning this [here](https://github.com/medic/cht-docs/pull/266#issuecomment-671481033).

**Review by nomulex — APPROVED** [review]
LGTM

**Comment by mrjones-plip** [comment]
@nomulex - Ohhh! I think don't think I fully understood your point earlier!  Well, next time we'll be sure to listen to you ;)  Thanks for the review!

**Pull request merged**
