### PR TITLE
Add link for more detail on including media

### PR DESCRIPTION
**Pull request by garethbowen**
#534

### CODE REVIEW

**Comment by garethbowen** [comment]
@newtewt I wondered about having a whole section for media, but I think this link covers most of it. What do you think?

**Comment by newtewt** [comment]
@garethbowen  added a section to convey further how to use cht-conf to upload images while uploading the forms

**Comment by garethbowen** [comment]
@newtewt Awesome, thanks! I think this is ready to merge?

**Review by newtewt — APPROVED** [review]
👍

**Pull request merged**
