### PR TITLE
Build Contact management folder

### PR DESCRIPTION
**Pull request by esthermmoturi**
Consolidating contact and user management content under the Building section. The outcome should be as shown in the screenshot below.
image

### CODE REVIEW

**Review by michaelkohn — CHANGES_REQUESTED** [review]
I'm not sure if it's a result of your changes or my environment, but none of the images are loading on this page. 

Screenshot 2024-09-24 at 3 54 20 PM

**Comment by esthermmoturi** [comment]
I am not sure what is causing that, this is how it looks on my end 
image

**Comment by esthermmoturi** [comment]
I have moved the images.Let's see if they load correctly on your end now.

**Review by michaelkohn — APPROVED** [review]
Cool. They do load now 👍🏼 

Screenshot 2024-09-25 at 8 07 52 AM

**Comment by esthermmoturi** [comment]
Thanks @michaelkohn

**Pull request merged**
