### PR TITLE
Adds XLSForm meta fields

### PR DESCRIPTION
**Pull request by abbyad**
Taken from https://github.com/medic/medic-docs/blob/91badc2a347f86fd2b42b1c9ab9527b5982ee9c0/configuration/forms.md#supported-xlsform-meta-fields

### CODE REVIEW

**Comment by abbyad** [comment]
@newtewt, you AT'ed this [back in 3.7](https://github.com/medic/cht-core/issues/5768#issuecomment-528425141), can you please confirm that it still works as expected, and review this docs change?

**Comment by newtewt** [comment]
I know this is a copy from the previous docs. Do you think it would be helpful to define exactly when those time stamps should take place?

**Comment by abbyad** [comment]
That makes sense, I'll update.

**Comment by abbyad** [comment]
Thanks for the comment @newtewt, now ready for review.

**Review by newtewt — APPROVED** [review]

**Review by garethbowen — APPROVED** [review]

**Pull request merged**
