### PR TITLE
fix spealling of helath -> health

### PR DESCRIPTION
**Pull request by mrjones-plip**
like the title says!

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@maremegaye  - let's get you using GitHub more!  This is a super easy review that I'll help you go through if you haven't done a review before.

Steps are:
1. open [this review](https://github.com/medic/cht-docs/pull/387)
1. make sure the title and body are accurate and descriptive
1. go to the [changes page](https://github.com/medic/cht-docs/pull/387/files) and review what has changed.  
1. if it:
   1. looks good - create a new review an approve the changes via the [changes page](https://github.com/medic/cht-docs/pull/387/files)
   1. looks bad - create a new review your requesting changes  via the [changes page](https://github.com/medic/cht-docs/pull/387/files)

**Comment by mrjones-plip** [comment]
@n-orlowski - oh, oop - sorry. `codeowners` makes it so an authorized approvers needs to approve this too I guess.  When you get a sec, review  please! Sorry for the back and forth notices.

**Review by n-orlowski — APPROVED** [review]
Approving for

**Review by maremegaye — APPROVED** [review]
LGTM

**Pull request merged**
