### PR TITLE
feat(#1061) Update architecture diagrams

### LINKED ISSUE #1061: Update Archicture Diagram: Add Watchdog, split into 3 diagrams
On the [architecture page](https://docs.communityhealthtoolkit.org/core/overview/architecture/), we should add [CHT Watchdog](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/setup/). to the diagram.  However, @garethbowen  suggests now that this diagram is getting complex, we should split it up into 3:
* CHT Core
* CHT Sync
* CHT Watchdog

We should also consider using Mermaid for this now that it's enabled.  Otherwise, the original diagram is [here in Google Slides](https://docs.google.com/presentation/d/1j4jPsi-gHbiaLBfgYOyru1g_YV98PkBrx2zs7bwhoEQ/edit#slide=id.p).

### PR DESCRIPTION
**Pull request by mrjones-plip**
This PR:
* Adds architecture diagrams for CHT Watchdog
* Splits Core, Watchdog, Sync  into 3 diagrams instead of one massive one

closes #1061

### CODE REVIEW

**Comment by mrjones-plip** [comment]
Before we go much further with Mermaid, how are we feeling about the output vs existing Google Slides? 

### Mermaid 
image

### Google Slides
image

cc @jkuester @garethbowen @andrablaj @Phil-Mwago

**Comment by garethbowen** [comment]
It's not great TBH. I'm not a mermaid expert but can we fix the lines intersecting with the labels (maybe make them left aligned?). It just feels more cluttered and harder to read - can we tweak whitespace to make it clearer?

**Comment by andrablaj** [comment]
@mrjones-plip My personal preference is the Mermaid option rather than Google Slides, because of the easy version control integration.

**Comment by mrjones-plip** [comment]
> can we fix the lines intersecting with the labels (maybe make them left aligned?). It just feels more cluttered and harder to read - can we tweak whitespace to make it clearer?

Short answer "no"

Longer answer - There are some very light tweaks we can make - but they're very light.  @jkuester  has spent more time w/ Mermaid than I have, but I think the strong points of it are simple diagrams and possibly some more complex sequence diagrams, but not "left align" and "add more whitespace".  You can do a lot of these with CSS on top of the output SVG, but at that point, I think the revision control benefits don't outweigh the CSS hacking.

I'll take a look and see if there's like holistic CSS we can add so all Mermaids get the pretty treatment, and not doing it painfully ad hoc.

**Comment by garethbowen** [comment]
I'd be tempted to look into the CSS solution - can the SVG elements be identified (custom element IDs, classes, etc)?

What this would mean is we could define a stylesheet that would apply to all architecture diagrams to keep them consistent and attractive. To me this is the other benefit of using mermaid, rather than everyone making their own gif of the diagram.

I definitely agree with @andrablaj that version control is a huge win here.

Let's play around with this some more to see if we can get version control and usability in the same solution.

**Comment by mrjones-plip** [comment]
I've given up on Mermaid when I found Aligning [subgraphs title alignment isn't fixed](https://github.com/mermaid-js/mermaid/issues/1209). (thus the arrows of ours go OVER the title :upside_down_face: ) - BUT!! @andrablaj thinks we can make it work!  She offered to do some research to fix this!

**Comment by andrablaj** [comment]
Unfortunately, that's the best I got at the moment. I used the LR setup rather than the TB we used to have, but it is still not great. 

Screenshot 2023-05-09 at 18 35 39

**Comment by mrjones-plip** [comment]
nice work @andrablaj !  I don't think it's perfect, but it's improved for sure.

So maybe our saving grace is that maybe we don't need the "CHT Core Framework" label in there because we're splitting the diagrams up? with out that this would maybe look good enough?

**Comment by garethbowen** [comment]
Surely we can solve this with CSS?! I'll have a hack in a bit...

**Comment by mrjones-plip** [comment]
@garethbowen  - happy to co-hack real time if you want a second set of eyes! 

Otherwise, I found the SVG DOM elements aren't 100% responsive to CSS - I might be missing some SVG fu though!

**Comment by garethbowen** [comment]
CSS works as intended, however because mermaid generates SVGs with absolute positioned elements, adding padding just pushes the text into other elements, and even clipping it if it gets pushed beyond the element border. So it's not a simple css rule.

However mermaid can be configured to add more padding and styling: https://mermaid.js.org/config/setup/modules/mermaidAPI.html#mermaidapi-configuration-defaults

So maybe if we tweaked config.flowchart.diagramPadding it would help. But I can't for the life of me figure out where this config is or how to override it. It doesn't look like we're adding it anywhere and Hugo's documentation says it [doesn't exist](https://gohugo.io/content-management/diagrams/#mermaid-diagrams). Does anyone have more up to date Hugo docs? Or, any idea how it's being inited?

**Comment by andrablaj** [comment]
@garethbowen @mrjones-plip I just pushed a commit with the changes I did to get to [this version](https://github.com/medic/cht-docs/pull/1062#issuecomment-1540687867).

@garethbowen the commit should answer your question about the Mermaid configurations, which I added in the `config.toml` file and work correctly.

I also used the [Mermaid playground ](https://mermaid.live/edit#pako:eNqVVfFL4zAU_ldCBZnQgaLzvHIcTMVTOGW4OzhulZE1r22wTUKaOof4v9_LknXZnMr9UJrmve-9L-99r3mJMskgSqJU5JWcZyXVhvy8T0UqKi4ex2ZRAWGQ07YypDFaPkJ_zpkpkyP1bL2adlZoqkqSVRyESQXBFW2aS8j91lRgBpLzqkr2WA4UaOwCJXtfstnx7HgXhsETzyCE5of5Sc466NkJPcoPLdQ-HQuq1HSm5bwBPRkqRc7d-sE6EaJkm5VsNumN7OLy_OAhSZKApfNqlocOIn1GHgTbSYQKpiVnk6F7EyTkiQTWju6K6seUPOp_KNXNlBaFhoIaqSdpNL4dE0-j206jHXktEq0wp4sNmN_biUFCptUwVaUU0Eyu3Cdxn4F_0GCXCoXnnKaGzip8ZbJWrQHd2Nxrc0yWdoMLfwjBSOe7wWkrxyY18q3f_x4ekexvleozXi5CqJP9sEWOHRcGUBGGS2EPchN8Ooc5NyWRpgTtW71oDNTNjuIuexpMHGZ8cqj1EJYG-WmYXFz_Ihe4IFea1jCX-tErbz1o3jWcMYB8kH_t5HR6RgfZmcO1CjMwmNqkWNReGv12O74LhIydJY0OLPEwus-8Gr6LcPje-pVUafm86F0PR_b9TjSqeG84unnH2mDVuICqN_aLd_xEwcVz7-7Hzd2fgw_ZENtqf4KOwHJzqzCoAQ_ZZEKcVniQd3PLjfiKgWuIQN1tdSPe_gnHmaykDpvVzf5KMBuq9jJfi97_FDfFG0g6VPBS8UvyNnCnJWnnYVpo2ao3xPuMNniraLpIyIAMPMr_52On4TBAKqI4qkHXlDO8l16WR4lwPmqUVoJLAa3RtEqj2Jm6e8uaX1wx0yhrMbAD4EUGVHt_a7PdHSuacVFYj-PDzqIp3nlry-nawjjFItQjypg3WstrKl6RLm2NHC9EFiVGtxBHrWJY3ksHWW0C41j-W3fdZlLkvECoouKvlOiU06qB13-GC6WG) to play around with those configs. I hope it helps.

**Comment by mrjones-plip** [comment]
Love that Mermaid playground link!

**Comment by garethbowen** [comment]
@andrablaj Oh man! I tried the config.toml approach and didn't get it to work but maybe my syntax was off a bit. Thanks!

**Comment by garethbowen** [comment]
With a few tweaks I've made some small improvements, but because of the absolute positioning of the elements there's no way to have fine grained control. We need to weigh up the version control and ease of updates, with the reduced usability and aesthetic...

**Comment by mrjones-plip** [comment]
Mermaid may be able to do this, but moving along w/ PNGs from [the google slide](https://docs.google.com/presentation/d/1j4jPsi-gHbiaLBfgYOyru1g_YV98PkBrx2zs7bwhoEQ/edit#slide=id.p) (which has been updated obvs)

**Comment by mrjones-plip** [comment]
@jkuester  - in the context of literally explaining what each item does in watchdog, it felt a lot more clean to pull out the description of each item in the diagram:

image

**Review by garethbowen — CHANGES_REQUESTED** [review]
Very nice. This will make it much easier to talk about how all these new services fit together.

Some changes for the diagrams...

1. In the Core Framework diagram, I think CHT Sync and CHT Watchdog both technically go through nginx, api, haproxy, before getting to couchdb. If I'm right, then those arrows should be updated, and I would suggest we should move them above the client line, beside "integration with other systems". They should also square corner boxes because they're products in their own right.
2. In the Sync diagram, I think you can cut out the "CouchDB" bit, and just have a box for "CHT Core Framework" with nothing in it, matching the "Browser" box.
3. In the Sync diagram, to match the Core Framework diagram, I'd put the "Browser" and "Core Framework" boxes above the CHT Sync box and passing requests in. I think that makes it clearer how they interact.
4. Similarly with the Watchdog diagram you don't need to have the "API", "CouchDB", or "couch2pg" boxes and lines. Treat the Core Framework and RDBMS as black boxes.
5. Also in the Watchdog diagram, if you can I think it'd be clearer to move Prometheus under Grafana so there's a clear top-down flow, but that'll make a long skinny diagram, so it's up to you...
6. In the original we coloured CHT Sync yellow to differentiate it. Consider finding a new colour scheme for CHT Watchdog for the same reason. Nicole may be able to help here...

**Comment by mrjones-plip** [comment]
@garethbowen  - thanks so much for the feedback!  All 6 points should be addressed in bf9bd749.

**Review by garethbowen — APPROVED** [review]
Awesome! Thanks for sorting this out.

**Comment by mrjones-plip** [comment]
@andrablaj @Phil-Mwago @jkuester - i know i'm zooooming ahead without y'all!  My thinking is that we should be iterative and go live as soon as we can.  I'll take no offense if y'all see mistakes that need fixing (I'll help!) or if we need to redo of these to be accurate.

**Pull request merged**
