### PR TITLE
 chore: update targets page images

### PR DESCRIPTION
**Pull request by Benmuiruri**
# Description

Update images in [Targets page](https://docs.communityhealthtoolkit.org/apps/features/targets/) to showcase new material design cards

### Old 
Screenshot 2023-10-30 at 15 52 06

### New
Screenshot 2023-10-30 at 15 52 29

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by andrablaj — COMMENTED** [review]
Thanks @Benmuiruri! Are the old screenshots used somewhere? If not, I recommend deleting them. 

As I don't have the context of the target changes, I will also add @michaelkohn as a reviewer to confirm the screenshots are what we expect them to be on this page.

**Comment by Benmuiruri** [comment]
@andrablaj I don't think they are being referenced anywhere else. I will delete them. Thanks for adding Michael

**Comment by michaelkohn** [comment]
Here are some other places we'll probably need to update as well 

- [ ] https://docs.communityhealthtoolkit.org/apps/features/targets/#count-widgets
- [ ] https://docs.communityhealthtoolkit.org/apps/features/targets/#percent-widgets
- [ ] https://docs.communityhealthtoolkit.org/apps/reference/targets/
- [ ] https://docs.communityhealthtoolkit.org/design/best-practices/#targets

And maybe this one... though I'm less concerned with it
- [ ] https://docs.communityhealthtoolkit.org/apps/tutorials/targets/

**Comment by michaelkohn** [comment]
Oops, one more (for @n-orlowski ) .... we should update https://www.figma.com/file/Zl8TNPi7iNF0t5k0ZxSeId/Medic-Library?type=design&node-id=0-5430&mode=design as well

**Comment by andrablaj** [comment]
@Benmuiruri I removed myself as a reviewer and added @n-orlowski instead, as she has more knowledge about the design of the targets. It looks good to me, but I can't approve as I don't know the details of the targets change.

**Comment by Benmuiruri** [comment]
Thanks @andrablaj  I was not sure who to ask the review from 😄

**Comment by n-orlowski** [comment]
@Benmuiruri these looks great! Could we keep the same aspect ratio for the images so they're consistent with the other pages? (Mobile 640x1100 / Desktop 1440x1024)

**Comment by Benmuiruri** [comment]
Hi @n-orlowski I have updated the images with the requested resolutions. I opened the screenshots using _Preview_ and adjusted the size. However, I must say the targets-desktop image looks "off". Kindly confirm whether thats how it should look. Thank you.

**Comment by Benmuiruri** [comment]
Hi @michaelkohn. 

This is ready for a review.

**Comment by michaelkohn** [comment]
Thanks @Benmuiruri ! For some reason it looks like some of the images are squished, not a lot, but noticeable 

### _Mobile looks fine but desktop looks squished horizontally_
Screenshot 2023-11-13 at 10 31 07 AM

### _Count widgets look fine but % widgets look squished vertically_

Screenshot 2023-11-13 at 10 36 51 AM

**Comment by michaelkohn** [comment]
(though to be clear, i wouldn't want this to hold up the release of 4.5.0)

**Comment by Benmuiruri** [comment]
Hi @michaelkohn , I updated the three images.

**Review by michaelkohn — APPROVED** [review]
Looks good to me! SHIPPPPPIIITTT

**Pull request merged**
