### PR TITLE
chore(): remove use of docker-compose command    

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

per #medic/cht-core/issues/8781

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by tatilepizs — COMMENTED** [review]
Thank you for doing these changes @mrjones-plip ⭐ 

I was checking and found these places where I think we need to change it also to `docker compose` could you please check?

- [content/en/hosting/3.x/_index.md L11](https://github.com/medic/cht-docs/blob/cht-core8781-remove-compose-v1/content/en/hosting/3.x/_index.md?plain=1#L11)
- [content/en/hosting/3.x/ssl-cert-install.md L17](https://github.com/medic/cht-docs/blob/cht-core8781-remove-compose-v1/content/en/hosting/3.x/ssl-cert-install.md?plain=1#L17)
- [content/en/hosting/4.x/_index.md L12](https://github.com/medic/cht-docs/blob/cht-core8781-remove-compose-v1/content/en/hosting/4.x/_index.md?plain=1#L12)
- [content/en/hosting/4.x/data-migration.md L131](https://github.com/medic/cht-docs/blob/cht-core8781-remove-compose-v1/content/en/hosting/4.x/data-migration.md?plain=1#L131)
- [content/en/hosting/4.x/data-migration.md L199](https://github.com/medic/cht-docs/blob/cht-core8781-remove-compose-v1/content/en/hosting/4.x/data-migration.md?plain=1#L199)

**Comment by mrjones-plip** [comment]
yes!  thank so much for catching those.  Should all be fixed in ddd6d3dc

**Review by tatilepizs — APPROVED** [review]
Thank you! 🚀 

Just one small thing, in the title it says `docker-helper` instead of `docker-compose` 😅

**Comment by mrjones-plip** [comment]
you're the best!!

**Pull request merged**
