### PR TITLE
migrate from emoji to simple X for tabular schedules, supporting changes for same

### LINKED ISSUE #424: tabular schedule render issues
@maremegaye  and I were testing out the new [tabular schedules](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#tabular-schedules) feature in her [MNCH docs branch](https://github.com/medic/cht-docs/pull/422).  We found that the table:
* does not always wrap the headers, so some are one line, others are on two (they should all be the same, preferably 2 lines)
* does not show the emoji for all browsers

For @maremegaye, her Safari and Chrome doesn't wrap.  I'm able to reproduce the same no wrap issue and also emoji do not show up on my older MacOS version running High Sierra 10.13.6 (build 17G14042 from November 2020). Line wrap works correctly in FireFox, but emoji is still broken.

Here's screenshots of the [docs style guide URL](https://docs.communityhealthtoolkit.org/contribute/docs/style-guide/#tabular-schedules).  Note all versions include browser version in them (should be latest of everything as of now)

Firefox:

[](https://user-images.githubusercontent.com/8253488/106798195-831b9700-6612-11eb-9a27-d81f1f2a1299.png)

Chrome:

[](https://user-images.githubusercontent.com/8253488/106798213-8a42a500-6612-11eb-8981-a1e9432c37a5.png)

Safari:

[](https://user-images.githubusercontent.com/8253488/106798226-8f075900-6612-11eb-9de7-b24921d2ae1a.png)

FYI @abbyad

### PR DESCRIPTION
**Pull request by mrjones-plip**
Fixes #424

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@abbyad - your windows testing love would be most welcome (obvs ;)

**Comment by mrjones-plip** [comment]
@abbyad  said:

> The headers are left aligned, which looks a bit off (to me). what do you think of this?
> [](https://user-images.githubusercontent.com/8253488/106841025-217d1c00-6656-11eb-8615-092223d66d5d.png)

to which I replied:

> yeah - that works! i'll update the PR...

and this is done in 6b50a7b - ready for another review @abbyad !

**Review by abbyad — APPROVED** [review]
This looks clean!

Looks like any text works to mark events, not just an upper case X - is that correct? Either way, approved!

**Comment by mrjones-plip** [comment]
> Looks like any text works to mark events, not just an upper case X - is that correct?

shhhh! it's our little secrete ;)  

Jokes aside, you're correct, but I opted for explicit instructions so as avoid folks from using something that might break it. Given I make it `font-size: 1pt;` nothing is really going to show, but you know, better safe than sorry.

**Pull request merged**
