### PR TITLE
Change recommended Enketo form test branch to enketo_upgrade_3.x

### PR DESCRIPTION
**Pull request by jkuester**
Updates the recommended branch for testing forms with the new version of Enketo on `3.x` architecture to be `enketo_upgrade_3.x`.

FWIW, I did a smoke test and was able to upgrade from `3.13.0` to `enketo_upgrade_3.x` with no issues. I also tried submitting several default forms and did not experience any issues.

### CODE REVIEW

**Review by mrjones-plip — CHANGES_REQUESTED** [review]
Rad - thank you!

Screenshot provided in PR is blurry.  Please use this one instead:

image

**Comment by mrjones-plip** [comment]
ah - I see you matched the old image pixel width and height perfect - so prob got fuzzy in the resize.  Size isn't so important - but thank you - eye for detail :detective: !

**Comment by jkuester** [comment]
Shoot!  GIMP + late night PRs failed me....  Should be fixed now!

**Review by mrjones-plip — APPROVED** [review]
thanks!

lgtm

**Pull request merged**
