### PR TITLE
deprecate mention of old couch2pg

### PR DESCRIPTION
**Pull request by mrjones-plip**
# Description

deprecate mention of old couch2pg on CHT Sync and CHT Pipeline overview page

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by andrablaj — APPROVED** [review]
📦

**Comment by mrjones-plip** [comment]
someone beat me to the change! I'll rescind this change

**Comment by andrablaj** [comment]
@mrjones-plip per the discussion in [Slack](https://medic.slack.com/archives/C03SP4KRVEX/p1725440176763459), should we just remove this paragraph altogether?

**Comment by mrjones-plip** [comment]
@andrablaj  - yah - maybe?  However, I think we might keep the other items on there (dbt et al.)  and couch2pg v2 possibly has a home on just this one page.  

I'll leave it as is for on now and as we revise docs we can further refine or further cull.

cc @Phil-Mwago

**Pull request closed without merging**
