### PR TITLE
Improve workflow headers

### PR DESCRIPTION
**Pull request by abbyad**
Improves header alignment in desktop view, and adds header for all mobile views.

For #267.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
Cool cool! I'll hop on this later today.

**Comment by abbyad** [comment]
Thanks, I want to make the path checker a little more tolerant so moving to a draft for now.

**Comment by mrjones-plip** [comment]
All good! Ping me when it's ready.

**Comment by abbyad** [comment]
Ready again, now with a more robust path checker which doesn't dictate file structure.

**Comment by mrjones-plip** [comment]
We have only 2 of these tables in use currently on the "Maternal and Newborn Health Reference App" page ([dev URL](http://localhost:1313/apps/examples/anc/)):

```bash
grep -r ' workflow-table' content/en
content/en/apps/examples/anc.md:{{% workflow-table
content/en/apps/examples/anc.md:{{% workflow-table
```

I see no regressions on desktop or mobile!  On to code/syntax/css review now.

**Comment by abbyad** [comment]
That's a weird one!

I can reproduce it _only_ in a dev setup, as in when file changes are triggering a rebuild of the site. I wasn't able to figure out a way for a fresh `hugo server` after any change to behave in an unexpected way. I would expect `hugo server --disableFastRender` to work the same way as a fresh run and catch errors, but it doesn't. 

This scenario can be reproduced in a simplified form too:

## 1. Create these files

### layouts\shortcodes\error.html
```html
{{ errorf "ERROR: %s" .Position }}
We shouldn't be here! 
First argument: "{{ .Get 0}}"
```

### content\en\test.md (blank)
```md
```

## 2. Run `hugo server --disableFastRender`: Build passes, as expected.

## 3. Edit md file as shown, see build fail, as expected

### content\en\test.md 
```md
This shortcode _should_ prevent builds. {{< test-error arg >}}
```

## 4. Resave the exact same file, see build pass, NOT expected

## 5. In `test.md` change `arg` to `anything`, see build pass, NOT expected

By using the shortcode in the example we can see that this isn't a simple partial/shortcode caching issue -- the page is generated with the shortcode argument.

**Given that our GH Action should catch issues like this, I don't think this needs to block this PR.** 

We can follow up with Hugo via their [discourse forum](https://discourse.gohugo.io/) first, and then [GH issues](https://github.com/gohugoio/hugo/issues).

**Comment by mrjones-plip** [comment]
@abbyad  - thanks for the fix on the comment line wrap and thanks for checking out that crazy file exists checking race condition! 

lgtm

**Pull request merged**
