### PR TITLE
Fix failing cht-docs builds: add broswerslist key to package.json

### PR DESCRIPTION
**Pull request by smbuthia**
I got the following error when I merged PR 469 to master:
```
TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Browsers.prefix (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/browsers.js:76:23)
    at /home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:174:31
    at Array.map (<anonymous>)
    at _loop (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:173:31)
    at Prefixes.select (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:198:7)
    at new Prefixes (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:98:49)
    at loadPrefixes (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/autoprefixer.js:102:20)
    at plugin (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/autoprefixer.js:109:20)
    at LazyResult.run (/home/runner/work/cht-docs/cht-docs/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/home/runner/work/cht-docs/cht-docs/node_modules/postcss/lib/lazy-result.js:212:26)
Building sites … Total in 2452 ms
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): Replace Autoprefixer browsers option to Browserslist config.
```

From [this link](https://github.com/browserslist/browserslist#browserslist-), I need to update package.json to include a `browserslist` key. Hopefully, this should fix the issue.

### CODE REVIEW

**Comment by mrjones-plip** [comment]
@latin-panda  - thanks for the suggestion!  I still don't quite feel like I'm a "node person", so it was my mistake to not use `npm ci` initially!  [Reading up on it](https://betterprogramming.pub/npm-ci-vs-npm-install-which-should-you-use-in-your-node-js-projects-51e07cb71e26), I can see the improvements.

@smbuthia and @n-orlowski - do we have a bit of time to to fix this to incorporate @latin-panda's suggestion or is your PR pressing to get live?

@smbuthia - you feel like taking `npm ci` on?  

Separately - I'll do some more research on the error to ensure I understand the proposed `browserslist` based fix.

**Comment by mrjones-plip** [comment]
To add a bit more detail is that it's dying on `run: hugo` [here](https://github.com/medic/cht-docs/blob/1b443094198dce1f0a744e23d6c1378893f3c804/.github/workflows/ci.yml#L41) and the full stack trace from [the GH Actions run](https://github.com/medic/cht-docs/runs/2542742331?check_suite_focus=true#step:7:18) is:

```
TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Browsers.prefix (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/browsers.js:76:23)
    at /home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:174:31
    at Array.map (<anonymous>)
    at _loop (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:173:31)
    at Prefixes.select (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:198:7)
    at new Prefixes (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:98:49)
    at loadPrefixes (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/autoprefixer.js:102:20)
    at plugin (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/autoprefixer.js:109:20)
    at LazyResult.run (/home/runner/work/cht-docs/cht-docs/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/home/runner/work/cht-docs/cht-docs/node_modules/postcss/lib/lazy-result.js:212:26)
Building sites … Total in 2452 ms
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Browsers.prefix (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/browsers.js:76:23)
    at /home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:174:31
    at Array.map (<anonymous>)
    at _loop (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:173:31)
    at Prefixes.select (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:198:7)
    at new Prefixes (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/prefixes.js:98:49)
    at loadPrefixes (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/autoprefixer.js:102:20)
    at plugin (/home/runner/work/cht-docs/cht-docs/node_modules/autoprefixer/lib/autoprefixer.js:109:20)
    at LazyResult.run (/home/runner/work/cht-docs/cht-docs/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/home/runner/work/cht-docs/cht-docs/node_modules/postcss/lib/lazy-result.js:212:26)
Error: Process completed with exit code 255.
```

**Comment by smbuthia** [comment]
@mrjones-plip the PR is not pressing to get live. @latin-panda I've added the `package-lock` and changed `npm install` to `npm ci`.

**Comment by mrjones-plip** [comment]
@binokaryg  and @latin-panda  - we're aware there's a backlog of builds that are being blocked by this.  Please be patient while @smbuthia  and I resolve the issue.  Thank you!

**Comment by mrjones-plip** [comment]
@smbuthia and @latin-panda - I really didn't like that we [already pinned the versions in CI](https://github.com/medic/cht-docs/pull/314/files) and yet this still broke. I built a container with the exact same `npm` and `hugo` versions as GHA uses in CI and couldn't reproduce the problem.  Then I was like "what if it was just a moment where GHA was unhappy?"  I re-ran all the broken jobs and [they all passed](https://github.com/medic/cht-docs/actions)!  So, while we're trading one problem (our CI code is broken, this PR is a fix) for another problem (random CI bug on GHA), I'd prefer to to fix this problem as it's not actually broken ;)  

I'm going to close the PR and not merge it.  If the problem comes up again and we can't fix it, I know I've gotten awesome engineers like @latin-panda  and @smbuthia  to help!  Thanks again @smbuthia  for the late night commit to this PR for the `package-lock` file for `npm ci`!

**Pull request closed without merging**
