### PR TITLE
app_settings should no longer be directly edited

### PR DESCRIPTION
**Pull request by njogz**
Make it clear that the app_settings.json is now more of a generated file and shouldn't be edited.

### CODE REVIEW

**Comment by newtewt** [comment]
I think these also need updated for the latest changes as well. 

https://docs.communityhealthtoolkit.org/apps/tutorials/sms-forms/

https://docs.communityhealthtoolkit.org/apps/tutorials/sms-schedules/

**Review by newtewt — APPROVED** [review]
Nice updates!

**Review by smbuthia — APPROVED** [review]
The tutorial updates look good to me.

**Comment by smbuthia** [comment]
Added `Blocked` label so this isn't accidentally merged before the changes are released.

**Review by garethbowen — APPROVED** [review]

**Pull request merged**
