### PR TITLE
Update docker image

### PR DESCRIPTION
**Pull request by ronna**
Update Docker image to the latest
see: https://github.com/medic/cht-infrastructure/pull/4

### CODE REVIEW

**Comment by ronna** [comment]
Please do not merge, there seems to be an issue starting CouchDB with the updated medic-os docker image: https://github.com/medic/cht-infrastructure/issues/5

**Comment by mrjones-plip** [comment]
@ronna - Soooo sorry to bomb your PR with all my commits!  I'd meant to be referencing `259` this whole time.  Unfortunately, I was testing something on GH Actions which meant I needed to push every time I needed to test : (

**Review by garethbowen — CHANGES_REQUESTED** [review]
Nice one! Thanks!

I think we should also change the `version` value on line 41.

**Comment by mrjones-plip** [comment]
FYI - The docker compose file was updated [in cht-infrastructure](https://github.com/medic/cht-infrastructure/blob/master/self-hosting/main/docker-compose.yml) to be even more current: `cht-3.7.0-rc.1` -> `cht-3.9.0-rc.2`.

Also - line 41 `version = 3.7` is correct as it's a yaml versioning thing, not a CHT thing.  Nick, unsurprisingly, [set me straight](https://github.com/medic/cht-infrastructure/pull/6#discussion_r486704060).

**Comment by garethbowen** [comment]
Closing as I think this is now obsolete. Please reopen if I'm mistaken.

**Pull request closed without merging**
