### PR TITLE
Fix CI postcss error

### PR DESCRIPTION
**Pull request by mrjones-plip**
I'm gonna make a tshirt "@newtewt is my hero" (but let's hope it doesn't [infect all of GH](https://en.wikipedia.org/wiki/Samy_%28computer_worm%29) ;). With newtewt's help, he verified my initial hunch of `autoprefixer` versions upgrading out from under us was indeed the problem.  

Fix was to add a `package.json` and pin the versions. I went ahead pinned both `autoprefixer` and `postcss-cli`.

see  #313

@abbyad  or @nomulex - I don't think we need ya both to do a review.  First come, first served?  I'm easy. 

PR is ready for ya!

### CODE REVIEW

**Comment by abbyad** [comment]
I will leave this review to @nomulex so that the PR can benefit of his expertise.

**Comment by mrjones-plip** [comment]
Thanks @abbyad! 

@n-orlowski - while your build is still failing on GH, feel free to work with Max on the review since I see it's not broken when run on local dev machines. I just see that it's Alex's end of day where he is, so we might not get a fix out until tomorrow.

**Review by nomulex — APPROVED** [review]
LGTM
May be good to put a comment at the npm install stage  indicating that the packages are installed through packages.json so that if anyone whats to add any package, they go through that or if they want to upgrade the version of a package. Other than that. I see this passed [here](https://github.com/medic/cht-docs/runs/1125667582?check_suite_focus=true) so it's good to go.

**Comment by mrjones-plip** [comment]
Thanks Alex!

**Pull request merged**
