### PR TITLE
Move available hosting resources and fix links

### PR DESCRIPTION
**Pull request by esthermmoturi**
# Description

Moving the hosting section from a 3rd level navigation section to a top-level navigation section. 

per #1351

### CODE REVIEW

**Comment by esthermmoturi** [comment]
@mrjones-plip ,I didn't end up using the bash script to reroute the URLs (please see comment on #1351 ), I ended up doing it manually after running `hugo server `and getting directed to the URLs, since it was just a lift and move process it was easy to find and replace the URLs. I plan to use the bash script moving forward for the 'complicated' URL changes. I did manual test on the sections. Kindly let me know if you have any concerns.

**Review by mrjones-plip — CHANGES_REQUESTED** [review]
Nice work starting the effort get this moved!  Let's dive in to this PR and get it ready to publish live \o/

My first step was to test for `404`s from an outside perspective.  Currently there's 100% failure as all the old URLs `404` instead of redirecting:

```
http://localhost:1313/apps/guides/hosting/ 404
http://localhost:1313/apps/guides/hosting/3.x/ 404
http://localhost:1313/apps/guides/hosting/3.x/app-developer/ 404
http://localhost:1313/apps/guides/hosting/3.x/ec2-setup-guide/ 404
http://localhost:1313/apps/guides/hosting/3.x/offline/ 404
http://localhost:1313/apps/guides/hosting/3.x/self-hosting/ 404
http://localhost:1313/apps/guides/hosting/3.x/ssl-cert-install/ 404
http://localhost:1313/apps/guides/hosting/4.x/ 404
http://localhost:1313/apps/guides/hosting/4.x/adding-tls-certificates/ 404
http://localhost:1313/apps/guides/hosting/4.x/app-developer/ 404
http://localhost:1313/apps/guides/hosting/4.x/backups/ 404
http://localhost:1313/apps/guides/hosting/4.x/data-migration/ 404
http://localhost:1313/apps/guides/hosting/4.x/logs/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/multiple-nodes/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/self-hosting-k3s-multinode/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/single-node/ 404
http://localhost:1313/apps/guides/hosting/monitoring/ 404
http://localhost:1313/apps/guides/hosting/monitoring/integration/ 404
http://localhost:1313/apps/guides/hosting/monitoring/introduction/ 404
http://localhost:1313/apps/guides/hosting/monitoring/postgres-ingest/ 404
http://localhost:1313/apps/guides/hosting/monitoring/production/ 404
http://localhost:1313/apps/guides/hosting/monitoring/setup/ 404
http://localhost:1313/apps/guides/hosting/requirements/ 404
http://localhost:1313/apps/guides/hosting/vertical-vs-horizontal/ 404
```

Can you look into adding the correct [aliases](https://gohugo.io/content-management/urls/#aliases) and then run [the test steps again](https://github.com/medic/cht-docs/issues/1351#issuecomment-2062693922)?

Once you've fixed these issues, I'll give the PR another review.

**Comment by mrjones-plip** [comment]
@esthermmoturi - I noticed you hadn't clicked "request re-review" yet, but wasn't sure if you're ready for me to take another look.  I'll assume yes, but please excuse me if I'm premature! Next time I'll wait for you to press it :sweat_smile: :

image

nice work on the redirects with the `aliases`!  I think it'd be good to get your version of the [test script](https://github.com/medic/cht-docs/issues/1351#issuecomment-2062693922) running, that way you can easily test which URLs your missing (currently 4):

```
➜  cht-docs git:(hosting-top-level-migration) ✗ ./check.urls.sh hosting.urls.txt
http://localhost:1313/apps/guides/hosting/ 200
    -> http://localhost:1313/hosting/ 200 
http://localhost:1313/apps/guides/hosting/3.x/ 200
    -> http://localhost:1313/hosting/3.x/ 200 
http://localhost:1313/apps/guides/hosting/3.x/app-developer/ 200
    -> http://localhost:1313/hosting/3.x/app-developer/ 200 
http://localhost:1313/apps/guides/hosting/3.x/ec2-setup-guide/ 200
    -> http://localhost:1313/hosting/3.x/ec2-setup-guide/ 200 
http://localhost:1313/apps/guides/hosting/3.x/offline/ 404
http://localhost:1313/apps/guides/hosting/3.x/self-hosting/ 200
    -> http://localhost:1313/hosting/3.x/self-hosting/ 200 
http://localhost:1313/apps/guides/hosting/3.x/ssl-cert-install/ 200
    -> http://localhost:1313/hosting/3.x/ssl-cert-install/ 200 
http://localhost:1313/apps/guides/hosting/4.x/ 200
    -> http://localhost:1313/hosting/4.x/ 200 
http://localhost:1313/apps/guides/hosting/4.x/adding-tls-certificates/ 200
    -> http://localhost:1313/hosting/4.x/adding-tls-certificates/ 200 
http://localhost:1313/apps/guides/hosting/4.x/app-developer/ 200
    -> http://localhost:1313/hosting/4.x/app-developer/ 200 
http://localhost:1313/apps/guides/hosting/4.x/backups/ 200
    -> http://localhost:1313/hosting/4.x/backups/ 200 
http://localhost:1313/apps/guides/hosting/4.x/data-migration/ 200
    -> http://localhost:1313/hosting/4.x/data-migration/ 200 
http://localhost:1313/apps/guides/hosting/4.x/logs/ 200
    -> http://localhost:1313/hosting/4.x/logs/ 200 
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/multiple-nodes/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/self-hosting-k3s-multinode/ 404
http://localhost:1313/apps/guides/hosting/4.x/self-hosting/single-node/ 404
http://localhost:1313/apps/guides/hosting/monitoring/ 200
    -> http://localhost:1313/hosting/monitoring/introduction/ 200 
http://localhost:1313/apps/guides/hosting/monitoring/integration/ 200
    -> http://localhost:1313/hosting/monitoring/integration/ 200 
http://localhost:1313/apps/guides/hosting/monitoring/introduction/ 200
    -> http://localhost:1313/hosting/monitoring/introduction/ 200 
http://localhost:1313/apps/guides/hosting/monitoring/postgres-ingest/ 200
    -> http://localhost:1313/hosting/monitoring/postgres-ingest/ 200 
http://localhost:1313/apps/guides/hosting/monitoring/production/ 200
    -> http://localhost:1313/hosting/monitoring/production/ 200 
http://localhost:1313/apps/guides/hosting/monitoring/setup/ 200
    -> http://localhost:1313/hosting/monitoring/setup/ 200 
http://localhost:1313/apps/guides/hosting/requirements/ 200
    -> http://localhost:1313/hosting/requirements/ 200 
http://localhost:1313/apps/guides/hosting/vertical-vs-horizontal/ 200
    -> http://localhost:1313/hosting/vertical-vs-horizontal/ 200 
```

**Comment by mrjones-plip** [comment]
Also - I note there's been some upstream changes that you now need to resolve the conflicts on.  Let me know if you need a hand with this!

**Comment by esthermmoturi** [comment]
@mrjones-plip Before I fix the conflicts, I run the script, fixed the aliases for the 4 files that had unsuccessful redirects. I then ran the script again and I am still getting the 200 but no success exit code. Please let me know if you have any ideas what could be causing this.

> - /apps/guides/hosting/4.x/self-hosting
> - /apps/guides/hosting/4.x/self-hosting/multiple-nodes
> - /apps/guides/hosting/4.x/self-hosting/self-hosting-k3s-multinode
> - /apps/guides/hosting/4.x/self-hosting/single-node

**Comment by esthermmoturi** [comment]
@mrjones-plip , I think we are now good to go.I have had to manually fix the conflicts. The merge wasn't working due to the difference in directories.

**Review by mrjones-plip — APPROVED** [review]
Nice work making sure all those links and aliases are going to the right place!   Approving with possible follow up below you can tend to without me and without approval for any fixes.

I see some possible minor fixes needed here, but wasn't sure. I found them with a recursive `grep`:

```bash
grep -r 'apps/guides/hosting' content/en | grep -v 'content/en/hosting/' 
content/en/apps/guides/updates/preparing-for-4.md:  - /apps/guides/hosting/3.x/preparing-for-4.0
content/en/apps/guides/android/publishing.md:  /apps/guides/hosting/android-app/
content/en/contribute/code/core/dev-environment.md:  apps/guides/hosting/core-developer
```

**Comment by esthermmoturi** [comment]
Thanks @mrjones-plip , I have had a tough day while trying to fix the merge conflicts. I'll look into your comment and fix (if needed) in another PR.

**Pull request merged**
