### PR TITLE
feat: add contributor hall of fame

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

The security researcher hall of fame is something we've quoted in our docs but never had one because nobody has ever disclosed a vulnerability outside of Medic before. Until now!

This is what it looks like (on my machine).

image

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@andrablaj Would you mind reviewing this please?

**Review by andrablaj — APPROVED** [review]
Oh, this is so nice! 😍 

Not a blocker, but should we also consider repos such as:

- [cht-user-management](https://github.com/medic/cht-user-management)
- [cht-conf-test-harness](https://github.com/medic/cht-conf-test-harness)
- [cht-couch2pg](https://github.com/medic/cht-couch2pg)
- [cht-infrastructure](https://github.com/medic/cht-infrastructure) ?

**Comment by garethbowen** [comment]
Yes good catch! I've left cht-couch2pg out because it's deprecated IMO, but the other 3 are great.

**Comment by garethbowen** [comment]
@alxndrsn I can't add you as an official review but can you give me a thumbs up if this is how you'd like to be honoured?

**Comment by garethbowen** [comment]
Merging to clean this up. Will make further modifications as requested!

**Pull request merged**
