### PR TITLE
7068 Remove documentation about setting the user's language via the API

### PR DESCRIPTION
**Pull request by jkuester**
medic/cht-core#7068

The associated code changes are included on: https://github.com/medic/cht-core/pull/7081

### CODE REVIEW

**Review by dianabarsan — APPROVED** [review]
This is looking good.

**Comment by jkuester** [comment]
@dianabarsan, now that the [code has been merged](https://github.com/medic/cht-core/pull/7081), should I be good to merge this PR too?  (I am not sure if there is any special AT that needs to be done for these doc changes)

**Comment by dianabarsan** [comment]
@jkuester yes, merge away. The CI ... wait ... CI doesn't work for external contributors on cht-docs? 
Normally, the CI would be sufficient to be sure nothing is broken. Since the CI didn't start in this case, please run the "hugo" command locally to check that everything is in order before merging. (https://github.com/medic/cht-docs/blob/master/.github/workflows/ci.yml#L40)

cc @mrjones-plip

**Comment by dianabarsan** [comment]
Oh, now I get the question: it was the "Blocked: waiting for AT" label that was confusing? 
Some context for that: https://medic.slack.com/archives/C024KTGRW/p1622557871066100

**Comment by jkuester** [comment]
For the record, I was able to successfully run the `hugo` command locally.

**Comment by mrjones-plip** [comment]
@dianabarsan  and @jkuester  - PR is merged already, but do we need a `cht-docs` ticket to research if GH CI is working correctly for internal vs external contributions? I can imagine there might be some security measures in place so that [Mallory](https://en.wikipedia.org/wiki/Alice_and_Bob#Cast_of_characters
) can't run arbitrary code in a privileged CI environment, but that would more apply to `cht-core` than lil' ol' `cht-docs`.

Either way, lemme know!

**Comment by dianabarsan** [comment]
Thanks for the reply, @mrjones-plip . We do need a ticket for external contributors. 
In CHT-Core, what I've observed is that a user with write permissions has to click a button to initiate CI for an external contribution PR, so it becomes part of the code review process and is safe, as long as the reviewer makes sure no arbitrary dangerous code exists in the PR. I don't know if this is a setting in GitHub or just how things work by default.

**Comment by dianabarsan** [comment]
added issue: https://github.com/medic/cht-docs/issues/525

**Comment by mrjones-plip** [comment]
Awesome, thanks so much for filing that ticket @dianabarsan !  I'll follow up there.

**Pull request merged**
